# Generated by Django 2.2.6 on 2019-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('Id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Compra')),
                ('fornecedor', models.CharField(default=' ', max_length=255, verbose_name='Fornecedor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Total')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
