# Generated by Django 2.2.6 on 2019-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('capa', models.ImageField(upload_to='media', verbose_name='Capa')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('editora', models.CharField(max_length=255, verbose_name='Editora')),
                ('edicao', models.CharField(max_length=255, verbose_name='Edição')),
                ('ano', models.CharField(max_length=255, verbose_name='Ano')),
                ('paginas', models.CharField(max_length=255, verbose_name='Nº de Páginas')),
                ('genero', models.CharField(max_length=255, verbose_name='Gênero')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('is_new', models.BooleanField(default=False, verbose_name='Novo')),
                ('sinopse', models.CharField(max_length=255, verbose_name='Sinopse')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de venda')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
