# Generated by Django 2.2.6 on 2019-11-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='is_new',
            new_name='novo',
        ),
    ]
